[versions]
agp = "8.12.3"
appcompat = "1.7.1"
espressoCore = "3.7.0"
javaxInject = "1"
junit = "4.13.2"
junitVersion = "1.3.0"
mockitoCore = "5.20.0"


[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }


[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }